name: Dev Build

on:
  push:
    tags: [ v* ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build_test_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.200

      - name: Add Nuget Source
        run: dotnet nuget add source --username ${{ secrets.NUGET_DTE_USERNAME }} --password ${{ secrets.NUGET_DTE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/nihr-interoperability-platform/index.json"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        
      - name: GetVersion
        id: version
        uses: battila7/get-version-action@v2
      
      - name: Dotnet Nuget pack
        run: dotnet pack ./src/Dte.Reference.Data.Api.Client --configuration Release --output . --include-source -p:PackageVersion=${{ steps.version.outputs.version-without-v }}
      
      - name: Dotnet Nuget push
        run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_DTE_TOKEN }} --source https://nuget.pkg.github.com/nihr-interoperability-platform/index.json